server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${qt.datasource.host}:${qt.datasource.port}/${qt.datasource.database}?useSSL=false&serverTimezone=UTC&characterEncoding=utf-8
    username: ${qt.datasource.username}
    password: ${qt.datasource.password}
  servlet:
    multipart:
      # 单个文件的最大限制
      max-file-size: 5MB
      # 单次请求（可能包含多个文件）的最大限制
      max-request-size: 20MB

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hotaru.entity
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      hotaru:
        mapper: debug
        service: info
        controller: info

# SpringDoc 配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  # 重点：配置扫描的控制器包路径
  packages-to-scan: com.hotaru.controller

# Knife4j 配置
knife4j:
  enable: true
  setting:
    language: zh-CN
    enableSwaggerModels: true
    enableReloadCacheProject: true

qt:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: ${qt.jwt.admin-secret-key}
    # 设置jwt过期时间
    admin-ttl: ${qt.jwt.admin-ttl}
    # 设置前端传递过来的令牌名称
    admin-token-name: ${qt.jwt.admin-token-name}
  aliyun:
    oss:
      endpoint: ${qt.aliyun.endpoint}
      access-key-id: ${qt.aliyun.access-key-id}
      access-key-secret: ${qt.aliyun.access-key-secret}
      bucket-name: ${qt.aliyun.bucket-name}

