qt:
  datasource:
    host: localhost
    port: 3306
    database: qiantu_move
    username: root
    password: ${DATABASE_PASSWORD}
  jwt:
    admin-secret-key: ${JWT_SECRET_KEY}
    admin-ttl: 604800000 # 7天
    admin-token-name: token
    user-secret-key: ${JWT_SECRET_KEY}
    user-ttl: 604800000 # 7天
    user-token-name: token
  aliyun:
    oss:
      endpoint: ${ALIYUN_OSS_ENDPOINT}
      access-key-id: ${ALIYUN_OSS_ACCESS_KEY_ID}
      access-key-secret: ${ALIYUN_OSS_ACCESS_KEY_SECRET}
      bucket-name: ${ALIYUN_OSS_BUCKET_NAME}
  wx:
    appId: ${WX_APPID}
    appSecret: ${WX_SECRET}